#!/bin/bash

read -p "categorie + id (e.g. gRestaurants1): " pageCateogirID
read -p "Name: " name
read -p "Adresse: " address
read -p "URL: " url
read -p "Deutscher Text: " textDEU
read -p "Englischer Text: " textENG
read -p "Italienischer Text: " textIT
read -p "Next Database ID (used for carousel): " databaseIDforCarousel

echo "Pictures: Upload path is uploads/pictures"
read -p "1: " picture1
read -p "2: " picture2
read -p "3: " picture3
read -p "4: " picture4

echo "German Text: "
echo '<div class="col-md-6"><p class="undercatparagraph" data-toggle="modal" href="#'$pageCategorieID'" style="color:rgb(255,255,255);background-image:url(&quot;'$picture1'&quot;);">'$name'</p><div class="modal fade" role="dialog" tabindex="-1" id=\"'$pageCategorieID'"><div class="modal-dialog" role="document"><div class="modal-content"><div class="modal-header"><button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button><h4 class="modal-title">'$name'</h4></div><div class="modal-body"><div class="carousel slide" data-ride="carousel" id="carousel-'$databaseIDforCarousel'"><div class="carousel-inner" role="listbox"><div class="item active"><img src="'$picture2'" alt="Slide Image" class="slideimg"></div><div class="item"><img src="'$picture3'" alt="Slide Image" class="slideimg"></div><div class="item"><img src="'$picture4'" alt="Slide Image" class="slideimg"></div></div><div><a class="left carousel-control" href="#carousel-'$databaseIDforCarousel'" role="button" data-slide="prev"><i class="glyphicon glyphicon-chevron-left" style="color:#ffffff;"></i><span class="sr-only">Previous</span></a><a class="right carousel-control"href="#carousel-'$databaseIDforCarousel'" role="button" data-slide="next"><i class="glyphicon glyphicon-chevron-right" style="color:#ffffff;"></i><span class="sr-only">Next</span></a></div><ol class="carousel-indicators"><li data-target="#carousel-'$databaseIDforCarousel'" data-slide-to="0" class="active"></li><li data-target="#carousel-'$databaseIDforCarousel'" data-slide-to="1"></li><li data-target="#carousel-'$databaseIDforCarousel'" data-slide-to="2"></li></ol></div><p class="modaltext">'$address' - '$textDEU'<br></p><p class="modaltextlink"><a href="'$url'">'$url'</a><br></p></div></div></div></div></div>'

echo "English Text: "
echo '<div class="col-md-6"><p class="undercatparagraph" data-toggle="modal" href="#'$pageCategorieID'" style="color:rgb(255,255,255);background-image:url(&quot;'$picture1'&quot;);">'$name'</p><div class="modal fade" role="dialog" tabindex="-1" id=\"'$pageCategorieID'"><div class="modal-dialog" role="document"><div class="modal-content"><div class="modal-header"><button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button><h4 class="modal-title">'$name'</h4></div><div class="modal-body"><div class="carousel slide" data-ride="carousel" id="carousel-'$databaseIDforCarousel'"><div class="carousel-inner" role="listbox"><div class="item active"><img src="'$picture2'" alt="Slide Image" class="slideimg"></div><div class="item"><img src="'$picture3'" alt="Slide Image" class="slideimg"></div><div class="item"><img src="'$picture4'" alt="Slide Image" class="slideimg"></div></div><div><a class="left carousel-control" href="#carousel-'$databaseIDforCarousel'" role="button" data-slide="prev"><i class="glyphicon glyphicon-chevron-left" style="color:#ffffff;"></i><span class="sr-only">Previous</span></a><a class="right carousel-control"href="#carousel-'$databaseIDforCarousel'" role="button" data-slide="next"><i class="glyphicon glyphicon-chevron-right" style="color:#ffffff;"></i><span class="sr-only">Next</span></a></div><ol class="carousel-indicators"><li data-target="#carousel-'$databaseIDforCarousel'" data-slide-to="0" class="active"></li><li data-target="#carousel-'$databaseIDforCarousel'" data-slide-to="1"></li><li data-target="#carousel-'$databaseIDforCarousel'" data-slide-to="2"></li></ol></div><p class="modaltext">'$address' - '$textENG'<br></p><p class="modaltextlink"><a href="'$url'">'$url'</a><br></p></div></div></div></div></div>'

echo "Italian Text: "
echo '<div class="col-md-6"><p class="undercatparagraph" data-toggle="modal" href="#'$pageCategorieID'" style="color:rgb(255,255,255);background-image:url(&quot;'$picture1'&quot;);">'$name'</p><div class="modal fade" role="dialog" tabindex="-1" id=\"'$pageCategorieID'"><div class="modal-dialog" role="document"><div class="modal-content"><div class="modal-header"><button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">×</span></button><h4 class="modal-title">'$name'</h4></div><div class="modal-body"><div class="carousel slide" data-ride="carousel" id="carousel-'$databaseIDforCarousel'"><div class="carousel-inner" role="listbox"><div class="item active"><img src="'$picture2'" alt="Slide Image" class="slideimg"></div><div class="item"><img src="'$picture3'" alt="Slide Image" class="slideimg"></div><div class="item"><img src="'$picture4'" alt="Slide Image" class="slideimg"></div></div><div><a class="left carousel-control" href="#carousel-'$databaseIDforCarousel'" role="button" data-slide="prev"><i class="glyphicon glyphicon-chevron-left" style="color:#ffffff;"></i><span class="sr-only">Previous</span></a><a class="right carousel-control"href="#carousel-'$databaseIDforCarousel'" role="button" data-slide="next"><i class="glyphicon glyphicon-chevron-right" style="color:#ffffff;"></i><span class="sr-only">Next</span></a></div><ol class="carousel-indicators"><li data-target="#carousel-'$databaseIDforCarousel'" data-slide-to="0" class="active"></li><li data-target="#carousel-'$databaseIDforCarousel'" data-slide-to="1"></li><li data-target="#carousel-'$databaseIDforCarousel'" data-slide-to="2"></li></ol></div><p class="modaltext">'$address' - '$textIT'<br></p><p class="modaltextlink"><a href="'$url'">'$url'</a><br></p></div></div></div></div></div>'
